const ProductData = [
  {
    id: 1,
    name: 'Product 1',
    description: 'This is the description of Product 1.',
    price: 20,
    image: 'product1.jpg',
  },
  {
    id: 2,
    name: 'Product 2',
    description: 'A brief description of Product 2.',
    price: 30,
    image: 'product2.jpg',
  },
  {
    id: 3,
    name: 'Product 3',
    description: 'Description for Product 3.',
    price: 40,
    image: 'product3.jpg',
  },
  {
    id: 4,
    name: 'Product 4',
    description: 'Product 4 description goes here.',
    price: 50,
    image: 'product4.jpg',
  },
  {
    id: 5,
    name: 'Product 5',
    description: 'Description of Product 5.',
    price: 60,
    image: 'product5.jpg',
  },
  {
    id: 6,
    name: 'Product 5',
    description: 'Description of Product 5.',
    price: 70,
    image: 'product5.jpg',
  },
  {
    id: 7,
    name: 'Product 5',
    description: 'Description of Product 5.',
    price: 80,
    image: 'product5.jpg',
  },
  {
    id: 8,
    name: 'Product 6',
    description: 'Description of Product 6.',
    price: 90,
    image: 'product6.jpg',
  },
  {
    id: 9,
    name: 'Product 7',
    description: 'Description of Product 7.',
    price: 100,
    image: 'product7.jpg',
  },
  {
    id: 10,
    name: 'Product 8',
    description: 'Description of Product 8.',
    price: 70,
    image: 'product8.jpg',
  },
  {
    id: 11,
    name: 'Product 9',
    description: 'Description of Product 9.',
    price: 120,
    image: 'product9.jpg',
  },
  {
    id: 12,
    name: 'Product 10',
    description: 'Description of Product 10.',
    price: 85,
    image: 'product10.jpg',
  },
  {
    id: 13,
    name: 'Product 11',
    description: 'Description of Product 11.',
    price: 110,
    image: 'product11.jpg',
  },
  {
    id: 14,
    name: 'Product 12',
    description: 'Description of Product 12.',
    price: 95,
    image: 'product12.jpg',
  },
  {
    id: 15,
    name: 'Product 13',
    description: 'Description of Product 13.',
    price: 75,
    image: 'product13.jpg',
  },
  {
    id: 16,
    name: 'Product 14',
    description: 'Description of Product 14.',
    price: 130,
    image: 'product14.jpg',
  },
  {
    id: 17,
    name: 'Product 15',
    description: 'Description of Product 15.',
    price: 88,
    image: 'product15.jpg',
  },
];

export default ProductData;
